#!/usr/bin/env python3
"""Generate binary-safe C boot files from a flat asset directory."""
import argparse
from pathlib import Path
import re


def generate(directory):
    files = sorted(directory.iterdir(), key=lambda path: path.name)
    if len(files) > 64:
        raise ValueError("embedded RAM filesystem supports at most 64 files")
    lines = ['/* Generated by scripts/embed-files.py; edit assets/ramfs instead. */',
             '#include <rum/embedded.h>', '#include <rum/ramfs.h>', '']
    entries = []
    for index, path in enumerate(files):
        if (not path.is_file() or path.is_symlink() or
                not re.fullmatch(r"[A-Za-z0-9._-]{1,63}", path.name) or path.name in (".", "..")):
            raise ValueError(f"invalid embedded filename: {path.name}")
        data = path.read_bytes()
        if len(data) > 65536:
            raise ValueError(f"embedded file exceeds 64 KiB: {path.name}")
        lines.append(f"static const unsigned char data_{index}[] = {{")
        for offset in range(0, len(data), 16):
            lines.append("    " + ", ".join(f"0x{byte:02x}" for byte in data[offset:offset + 16]) + ",")
        if not data:
            lines.append("    0,")
        lines.append("};")
        entries.append(f'    {{ "{path.name}", data_{index}, {len(data)} }},')
    lines.extend(['', 'const struct embedded_file embedded_files[] = {',
                  *entries, '    { NULL, NULL, 0 }', '};', '',
                  f'const size_t embedded_file_count = {len(files)};', '',
                  'bool embedded_files_install(void)', '{',
                  '    for (size_t i = 0; i < embedded_file_count; ++i)',
                  '        if (ramfs_read(embedded_files[i].name, NULL, NULL)) return false;',
                  '    for (size_t i = 0; i < embedded_file_count; ++i) {',
                  '        const struct embedded_file *file = &embedded_files[i];',
                  '        if (!ramfs_put(file->name, file->data, file->size)) {',
                  '            while (i) (void)ramfs_remove(embedded_files[--i].name);',
                  '            return false;', '        }', '    }',
                  '    return true;', '}', ''])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("directory", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    try:
        content = generate(args.directory)
    except (OSError, ValueError) as error:
        parser.exit(1, f"rum: {error}\n")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    # Run each build to catch asset deletions, but preserve mtime if unchanged.
    if not args.output.exists() or args.output.read_bytes() != content.encode():
        temporary = args.output.with_suffix(".tmp")
        temporary.write_bytes(content.encode())
        temporary.replace(args.output)


if __name__ == "__main__":
    main()
